Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
FilterInput = true
FilterOutput = true
LastUsedInput = "alsa_input.pci-0000_05_00.6.analog-stereo"
LastUsedOutput = "alsa_output.pci-0000_05_00.6.analog-stereo"
